# This docker-compose file runs an empty ldap server 
version: '2'
services:
  test:
    image: petzi/nginx-letsencrypt.example.frontend
    build:
      context: .
      dockerfile: Dockerfile.example.frontend
    environment:
      PROXY_MODE: "dev"
      PROXY_DOMAIN: "localhost"
      PROXY_BACKENDS: "localhost test-backend"
      PROXY_HTTP_PORT: "2080"
      PROXY_HTTPS_PORT: "2443"
      PROXY_STATIC_DIRS: "static,/extrahtml nothing,/var/www/html"
      PROXY_AUTH_USER: "test"
      PROXY_AUTH_PASSWORD: "password"
      PROXY_TUNING_UPSTREAM_MAX_CONNS: "32"
      PROXY_TUNING_WORKER_CONNECTIONS: "128"
      ENTRYPOINT_LOGLEVEL: 4
    ports:
      - "2080:2080"
      - "2443:2443"
    depends_on:
      - test-backend
    volumes_from:
      - test-backend

  test-backend:
    image: petzi/nginx-letsencrypt.example.backend
    build:
      context: .
      dockerfile: Dockerfile.example.backend
